language: node_js
node_js:
  - "iojs"
  - "7"
install:
  - npm install -g babel-cli
  - npm install
script: "mocha -g ^Unit:: --compilers js:babel-core/register --recursive"
after_success: "nyc report --reporter=text-lcov | coveralls"