language: node_js
node_js:
- iojs
- '7'
install:
- npm install -g babel-cli
- npm install
script: 'NODE_ENV=unit mocha -g ^Unit:: --compilers js:babel-core/register --recursive'
after_success: 'nyc _mocha -g ^Unit:: --compilers js:babel-core/register --recursive
  && nyc report --reporter=text-lcov | coveralls'
before_install:
- openssl aes-256-cbc -K $encrypted_0edd0fc670eb_key -iv $encrypted_0edd0fc670eb_iv
  -in config.js.enc -out lib/config.js -d
