language: node_js
node_js:
- iojs
- '7'
install:
- npm install -g babel-cli
- npm install

before_install:
- openssl aes-256-cbc -K $encrypted_f4c35811067e_key -iv $encrypted_f4c35811067e_iv -in lib/config.js.enc -out lib/config.js -d
env:
  NODE_ENV=unit
